### ISSUE TITLE
einzelne Würfel mit auf die Liste

### ISSUE THREAD

**Issue by Technickfreak** [letsgamedev/dicestatistics#2]
wäre es möglich in die liste noch die Würfel würfe mit auf zu nehmen die einzeln geworfen wurden?
zB:
WÜRFEL    Ø-WERT    BALKEN
0 4            ~2.0
0 6            ~3.0

**Comment by letsgamedev** [comment]
Diese sind bereits in der zweiten Tabbelle alle enthalten in der bis zu vier würfel aufgelistet sind.
